# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-21 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('week_date', models.CharField(blank=True, max_length=32)),
                ('week_trend', models.BigIntegerField(blank=True, null=True)),
                ('company_code', models.BigIntegerField(blank=True, null=True)),
                ('account_group', models.CharField(blank=True, db_column='account_group', max_length=32, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('credit_limit', models.CharField(blank=True, max_length=32, null=True)),
                ('outstanding_amount', models.CharField(blank=True, max_length=32, null=True)),
                ('not_due_amount', models.CharField(blank=True, max_length=32, null=True)),
                ('number_0_30_days_os', models.CharField(blank=True, db_column='0_30_Days_OS', max_length=32, null=True)),
                ('number_31_60_days_os', models.CharField(blank=True, db_column='31_60_Days_OS', max_length=32, null=True)),
                ('number_61_90_days_os', models.CharField(blank=True, db_column='61 _90_Days_OS', max_length=32, null=True)),
                ('number_91_120_days_os', models.CharField(blank=True, db_column='91_120_Days_OS', max_length=32, null=True)),
                ('number_121_180_days_os', models.CharField(blank=True, db_column='121_180_Days_OS', max_length=32, null=True)),
                ('number_181_365_days_os', models.CharField(blank=True, db_column='181_365_Days_OS', max_length=32, null=True)),
                ('greater_than_365_days_os', models.CharField(blank=True, db_column='greater_than_365_Days_OS', max_length=32, null=True)),
                ('overdue_amount', models.CharField(blank=True, max_length=32, null=True)),
                ('less_than_180_days_overdue', models.CharField(blank=True, db_column='less_than_180_Days_Overdue', max_length=32, null=True)),
                ('greater_than_180_days_overdue', models.CharField(blank=True, db_column='greater_than_180_Days_Overdue', max_length=32, null=True)),
                ('security_deposit', models.CharField(blank=True, max_length=32, null=True)),
                ('no_of_days_os', models.CharField(blank=True, db_column='No_of_Days_OS', max_length=32, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'dealer_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinalRatings',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('vintage_rating', models.BigIntegerField(blank=True, null=True)),
                ('severity_rating', models.BigIntegerField(blank=True, null=True)),
                ('growth_rating', models.BigIntegerField(blank=True, null=True)),
                ('u1_rating', models.BigIntegerField(blank=True, null=True)),
                ('u2_rating', models.BigIntegerField(blank=True, null=True)),
                ('recency_rating', models.FloatField(blank=True, null=True)),
                ('os_days_rating', models.BigIntegerField(blank=True, null=True)),
                ('instances_rating', models.BigIntegerField(blank=True, null=True)),
                ('repayment_outstanding_ratio_rating', models.BigIntegerField(blank=True, null=True)),
                ('final_rating', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'final_ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrowthRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'growth_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstancesRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'instances_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OsDaysRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'os_days_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.BigIntegerField(blank=True, db_column='dealerId', db_index=True, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=32)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.BigIntegerField(blank=True, null=True)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('week_trend', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'payment_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecencyRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'recency_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepaymentOutstandingRatio',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.BigIntegerField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('week_trend', models.BigIntegerField(blank=True, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'repayment_outstanding_ratio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepaymentOutstandingRatioRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'repayment_outstanding_ratio_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('sales_value', models.FloatField(blank=True, null=True)),
                ('month', models.BigIntegerField(blank=True, null=True)),
                ('date', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sales_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeverityRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'severity_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SumOutstanding',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('week_trend', models.BigIntegerField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sum_outstanding',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SumRepayment',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.BigIntegerField(blank=True, db_column='dealerId', db_index=True, null=True)),
                ('week_trend', models.BigIntegerField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sum_repayment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='U1Rating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'u1_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='U1Ratio',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'u1_ratio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='U2Rating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'u2_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='U2Ratio',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'u2_ratio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VintageRating',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dealerid', models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(db_column='upload_date', default=b'21/02/2017::06:03:45', max_length=32)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'vintage_rating',
                'managed': True,
            },
        ),
    ]
