# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdata',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dealerdata',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='growthrating',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='growthrating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='instancesrating',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='instancesrating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='osdaysrating',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='osdaysrating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='recencyrating',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recencyrating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='repaymentoutstandingratio',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='repaymentoutstandingratio',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='repaymentoutstandingratiorating',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='repaymentoutstandingratiorating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='severityrating',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='severityrating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='sumoutstanding',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sumoutstanding',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='sumrepayment',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sumrepayment',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='u1rating',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='u1rating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='u1ratio',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='u1ratio',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='u2rating',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='u2rating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='u2ratio',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='u2ratio',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
        migrations.AlterField(
            model_name='vintagerating',
            name='dealerid',
            field=models.CharField(blank=True, db_column='dealerId', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vintagerating',
            name='upload_date',
            field=models.CharField(db_column='upload_date', default=b'22/02/2017::11:59:32', max_length=32),
        ),
    ]
